### ISSUE TITLE
Add ability to provide few-shot examples

### ISSUE THREAD

**Issue by patrickstorm** [jamesturk/scrapeghost#13]
I was playing around with this and found that the scraping got way, way better when I provided one or two short HTML snippets and JSON output based on each. I was primarily interested in this project as a way to self-heal CSS selectors, and ran into similar issues where the selectors weren't 100% accurate. When I modified the code to allow me to add an example, the success rate went up to 100% in my handful of tests.

**Comment by jamesturk** [comment]
I’ve been exploring this too, do you have a couple of examples that work for you that you could share? I’m working on docs and tutorials now and could definitely incorporate an example of a page that needs one if you have one you found.

**Comment by jamesturk** [comment]
The latest version supports adding `extra_instructions` which allows for all kinds of customization.  Would love to add a multi-shot example if someone has one.

https://jamesturk.github.io/scrapeghost/tutorial/#extra-instructions
