### ISSUE TITLE
selenium intergration?

### ISSUE THREAD

**Issue by barshag** [jamesturk/scrapeghost#28]
Use case:

Fill forms and click on buttons online...

**Comment by jamesturk** [comment]
Hi! I definitely think there are a lot of ways to take this further but I have decided not to go down the rabbit hole of having the scraper interact with the page in any way. I feel like the ethical implications and potential risks are just beyond what I want to be worrying about here. A GET request is as far as this library is going to go in terms of interacting with the web.

As for working with headless browsers, I think one of the next things I'm going to try is to add a full-page-render option that'll allow this to work on pages that load info via JS.
