### ISSUE TITLE
Disable HallucinationChecker

### ISSUE THREAD

**Issue by kjenney** [jamesturk/scrapeghost#35]
Is there a way to disable HallucinationChecker? If so, how? If not, can we add the ability to do this?

**Comment by jamesturk** [comment]
Currently you can pass in your own list of postprocessors to override the default.  Just pass postprocessors=[JSONPostprocessor].

**Comment by kjenney** [comment]
Using the latest version and this code:

```
from scrapeghost import SchemaScraper
from pprint import pprint
from scrapeghost.postprocessors import JSONPostprocessor

scrape_legislators = SchemaScraper(
  postprocessors=[JSONPostprocessor],
  schema={
      "name": "string",
      "url": "url",
      "district": "string",
      "party": "string",
      "photo_url": "url",
      "offices": [{"name": "string", "address": "string", "phone": "string"}],
  }
)

resp = scrape_legislators("https://www.ilga.gov/house/rep.asp?MemberID=3071")
pprint(resp)
```

I'm getting the following error:

```
Traceback (most recent call last):
  File "/Users/ken/devel/python/scrapeghost/test.py", line 18, in <module>
    resp = scrape_legislators("https://www.ilga.gov/house/rep.asp?MemberID=3071")
  File "/usr/local/lib/python3.10/site-packages/scrapeghost/scrapers.py", line 142, in scrape
    return self._apply_postprocessors(  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/scrapeghost/apicall.py", line 213, in _apply_postprocessors
    response = pp(response, self)
  File "/usr/local/lib/python3.10/site-packages/scrapeghost/postprocessors.py", line 112, in __call__
    _check_data_in_html(html, response.data)
  File "/usr/local/lib/python3.10/site-packages/scrapeghost/postprocessors.py", line 123, in _check_data_in_html
    _check_data_in_html(html, v, parent + f".{k}")
  File "/usr/local/lib/python3.10/site-packages/scrapeghost/postprocessors.py", line 129, in _check_data_in_html
    raise PostprocessingError(f"Data not found in html: {d} (parent: {parent})")
scrapeghost.errors.PostprocessingError: Data not found in html: https://www.ilga.gov/house/Rep.asp?GA=102&MemberID=3071 (parent: .url)
```

**Comment by jamesturk** [comment]
Oh that's an interesting case -- I am going to disable HC by default and experiment more with it.

As for the override not working, looks like I messed something up in a refactor.  Just pushed a fix.

On Sun, Mar 26, 2023, at 6:55 PM, Ken Jenney wrote:
> 
> 
> Using the latest version and this code:
> 
> `from scrapeghost import SchemaScraper
> from pprint import pprint
> from scrapeghost.postprocessors import JSONPostprocessor
> 
> scrape_legislators = SchemaScraper(
>   postprocessors=[JSONPostprocessor],
>   schema={
>       "name": "string",
>       "url": "url",
>       "district": "string",
>       "party": "string",
>       "photo_url": "url",
>       "offices": [{"name": "string", "address": "string", "phone": "string"}],
>   }
> )
> 
> resp = scrape_legislators("https://www.ilga.gov/house/rep.asp?MemberID=3071")
> pprint(resp)
`
> I'm getting the following error:
> 
> `Traceback (most recent call last):
>   File "/Users/ken/devel/python/scrapeghost/test.py", line 18, in <module>
>     resp = scrape_legislators("https://www.ilga.gov/house/rep.asp?MemberID=3071")
>   File "/usr/local/lib/python3.10/site-packages/scrapeghost/scrapers.py", line 142, in scrape
>     return self._apply_postprocessors(  # type: ignore
>   File "/usr/local/lib/python3.10/site-packages/scrapeghost/apicall.py", line 213, in _apply_postprocessors
>     response = pp(response, self)
>   File "/usr/local/lib/python3.10/site-packages/scrapeghost/postprocessors.py", line 112, in __call__
>     _check_data_in_html(html, response.data)
>   File "/usr/local/lib/python3.10/site-packages/scrapeghost/postprocessors.py", line 123, in _check_data_in_html
>     _check_data_in_html(html, v, parent + f".{k}")
>   File "/usr/local/lib/python3.10/site-packages/scrapeghost/postprocessors.py", line 129, in _check_data_in_html
>     raise PostprocessingError(f"Data not found in html: {d} (parent: {parent})")
> scrapeghost.errors.PostprocessingError: Data not found in html: https://www.ilga.gov/house/Rep.asp?GA=102&MemberID=3071 (parent: .url)
`
