### ISSUE TITLE
Issue with release_date formatting in tutorial

### ISSUE THREAD

**Issue by christianboyle** [jamesturk/scrapeghost#37]
Following along with https://jamesturk.github.io/scrapeghost/tutorial/#enhancing-the-schema

Things are working as expected when using `"release_date": "str",`
![working](https://user-images.githubusercontent.com/1605754/229151035-bbb63a59-f09c-41e7-bfa7-1759ca41fb85.png)

Things break for me when you try to format that date using `"release_date": "YYYY-MM-DD",`
![broken](https://user-images.githubusercontent.com/1605754/229151375-35316b49-49c7-43c0-96e0-5563dc0d411e.png)

Any idea what could be causing this?

**Comment by jamesturk** [comment]
This is being triggered by the HallucinationChecker, which is overly aggressive in this case (the date in the format you specify isn't included, since it is converted automatically).

I'm just pushed a new release that deactivates it by default (0.4.4), upgrading will fix the issue.

**Comment by christianboyle** [comment]
Confirmed that 0.4.4 works. Thanks for the quick fix!
