### ISSUE TITLE
Extending the project for older python versions

### ISSUE THREAD

**Issue by enflo** [jamesturk/scrapeghost#43]
Currently the project only supports Python 3.10 or higher, it does not support versions like 3.8 or 3.9.

Otherwise, if backward compatibility does not open, please indicate with the badge which python versions are supported.

**Comment by jamesturk** [comment]
Hi,

Compatibility is expressed in the usual places (trove classifiers and pyproject.toml)

As indicated there, 3.10 is the intended target :)
