### ISSUE TITLE
JavaScript Enabling

### ISSUE THREAD

**Issue by PizhukDavidSCCH** [jamesturk/scrapeghost#56]
Some websites need js to be enabled to get HTML content. In scrapers.py you use Requests API to get content:
![image](https://github.com/jamesturk/scrapeghost/assets/110816868/0679f4e3-13a0-436f-aa8c-1b6724702148)
But with the first website I tried I got:
![image](https://github.com/jamesturk/scrapeghost/assets/110816868/d12ce4ed-ade7-400d-99d8-5e4c43186438)
I used library "playwright" to fix it:
![image](https://github.com/jamesturk/scrapeghost/assets/110816868/56b8b2ec-0041-4f32-b4f7-4f3d3e49fcc0)

**Comment by jamesturk** [comment]
The scrape method takes HTML for this reason, see this FAQ:

https://jamesturk.github.io/scrapeghost/faq/#can-i-use-httpx-or-seleniumplaywright-can-i-customize-the-headers-etc
