### ISSUE TITLE
Add support for gpt-4o-mini

### ISSUE THREAD

**Issue by DieterHolvoet** [jamesturk/scrapeghost#60]
The supported models seem to be hardcoded in `models.py`:
```
models = [
    Model("gpt-4", 0.03, 0.06, 8192, False),
    Model("gpt-4-32k", 0.06, 0.12, 32768, False),
    Model("gpt-4-1106-preview", 0.01, 0.03, 128000, True),
    Model("gpt-3.5-turbo", 0.001, 0.002, 16384, False),
    Model("gpt-3.5-turbo-1106", 0.001, 0.002, 16384, True),
]
```

Any chance we can support `gpt-4o-mini` as well?

**Comment by DieterHolvoet** [comment]
Here's the pricing information for this model: https://openai.com/api/pricing#MKm0TAT0sEESKMml2k65u

**Comment by jamesturk** [comment]
PRs are welcome but I haven't really had much reason to put work into this and don't see myself working w/ OpenAI again given their business practices, I may pick this up w/ other providers.
